services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appcopio_db
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  backend:
    image: node:22-bookworm
    working_dir: /workspace/appcopio-backend
    depends_on:
      - db
    env_file:
      - ./appcopio-backend/.env
    command: bash -lc "npm install && npm run dev"
    volumes:
      - .:/workspace:cached
      - backend_node_modules:/workspace/appcopio-backend/node_modules
    ports:
      - "4000:4000"

  frontend:
    image: node:22-bookworm
    working_dir: /workspace/appcopio-frontend
    depends_on:
      - backend
    command: bash -lc "npm install && npm run dev -- --host"
    volumes:
      - .:/workspace:cached
      - frontend_node_modules:/workspace/appcopio-frontend/node_modules
    ports:
      - "5173:5173"

volumes:
  dbdata:
  backend_node_modules:
  frontend_node_modules:
