// src/types/center.ts

// src/types/center.ts

export interface CenterData {
    center_id: string;
    name: string;
    address: string;
    type: 'Albergue' | 'Acopio' | '';
    capacity: number;
    latitude: number;
    longitude: number;
    should_be_active: boolean;
    comunity_charge_id: number | null;
    municipal_manager_id: number | null;

    // Campos de CentersDescription
    tipo_inmueble: string;
    numero_habitaciones: number | null;
    estado_conservacion: number | null;
    material_muros: number | null;
    material_pisos: number | null;
    material_techo: number | null;
    observaciones_acceso_y_espacios_comunes: string;
    espacio_10_afectados: number | null;
    diversidad_funcional: number | null;
    areas_comunes_accesibles: number | null;
    espacio_recreacion: number | null;
    observaciones_espacios_comunes: string;
    agua_potable: number | null;
    agua_estanques: number | null;
    electricidad: number | null;
    calefaccion: number | null;
    alcantarillado: number | null;
    observaciones_servicios_basicos: string;
    estado_banos: number | null;
    wc_proporcion_personas: number | null;
    banos_genero: number | null;
    banos_grupos_prioritarios: number | null;
    cierre_banos_emergencia: number | null;
    lavamanos_proporcion_personas: number | null;
    dispensadores_jabon: number | null;
    dispensadores_alcohol_gel: number | null;
    papeleros_banos: number | null;
    papeleros_cocina: number | null;
    duchas_proporcion_personas: number | null;
    lavadoras_proporcion_personas: number | null;
    observaciones_banos_y_servicios_higienicos: string;
    posee_habitaciones: number | null;
    separacion_familias: number | null;
    sala_lactancia: number | null;
    observaciones_distribucion_habitaciones: string;
    cuenta_con_mesas_sillas: number | null;
    cocina_comedor_adecuados: number | null;
    cuenta_equipamiento_basico_cocina: number | null;
    cuenta_con_refrigerador: number | null;
    cuenta_set_extraccion: number | null;
    observaciones_herramientas_mobiliario: string;
    sistema_evacuacion_definido: number | null;
    cuenta_con_senaleticas_adecuadas: number | null;
    observaciones_condiciones_seguridad_proteccion_generales: string;
    existe_lugar_animales_dentro: number | null;
    existe_lugar_animales_fuera: number | null;
    existe_jaula_mascota: boolean;
    existe_recipientes_mascota: boolean;
    existe_correa_bozal: boolean;
    reconoce_personas_dentro_de_su_comunidad: boolean;
    no_reconoce_personas_dentro_de_su_comunidad: boolean;
    observaciones_dimension_animal: string;
    existen_cascos: boolean;
    existen_gorros_cabello: boolean;
    existen_gafas: boolean;
    existen_caretas: boolean;
    existen_mascarillas: boolean;
    existen_respiradores: boolean;
    existen_mascaras_gas: boolean;
    existen_guantes_latex: boolean;
    existen_mangas_protectoras: boolean;
    existen_calzados_seguridad: boolean;
    existen_botas_impermeables: boolean;
    existen_chalecos_reflectantes: boolean;
    existen_overoles_trajes: boolean;
    existen_camillas_catre: boolean;
    existen_alarmas_incendios: boolean;
    existen_hidrantes_mangueras: boolean;
    existen_senaleticas: boolean;
    existen_luces_emergencias: boolean;
    existen_extintores: boolean;
    existen_generadores: boolean;
    existen_baterias_externas: boolean;
    existen_altavoces: boolean;
    existen_botones_alarmas: boolean;
    existen_sistemas_monitoreo: boolean;
    existen_radio_recargable: boolean;
    existen_barandillas_escaleras: boolean;
    existen_puertas_emergencia_rapida: boolean;
    existen_rampas: boolean;
    existen_ascensores_emergencia: boolean;
    observaciones_seguridad_comunitaria: string;
    importa_elementos_seguridad: boolean;
    observaciones_importa_elementos_seguridad: string;
    importa_conocimientos_capacitaciones: boolean;
    observaciones_importa_conocimientos_capacitaciones: string;
}